# Generated by Django 4.2.4 on 2023-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='titre',
            field=models.CharField(choices=[('Bonne_affaire', 'Bonne_affaire'), ('Nouvelle_arrivage', 'Nouvelle_arrivage')], max_length=100),
        ),
    ]
