# Generated by Django 4.2.4 on 2023-08-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0002_alter_slider_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/banner_img')),
            ],
        ),
    ]
