# Generated by Django 4.2.4 on 2023-08-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='titre',
            field=models.CharField(choices=[('Nouvelle_arrivage', 'Nouvelle_arrivage'), ('Bonne_affaire', 'Bonne_affaire')], max_length=100),
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomme.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomme.main_category'),
        ),
    ]
