# Generated by Django 4.2.4 on 2023-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0005_alter_slider_titre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.AlterField(
            model_name='slider',
            name='titre',
            field=models.CharField(choices=[('Nouvelle_arrivage', 'Nouvelle_arrivage'), ('Bonne_affaire', 'Bonne_affaire')], max_length=100),
        ),
    ]
