# Generated by Django 4.2.4 on 2023-08-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0006_rename_category_categorie_alter_slider_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_total', models.IntegerField()),
                ('disponibilite', models.IntegerField()),
                ('images', models.ImageField(upload_to='produit/produit_img')),
                ('nom_produit', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('rabais', models.IntegerField()),
                ('info_produit', models.TextField()),
                ('nom_model', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomme.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='titre',
            field=models.CharField(choices=[('Bonne_affaire', 'Bonne_affaire'), ('Nouvelle_arrivage', 'Nouvelle_arrivage')], max_length=100),
        ),
        migrations.CreateModel(
            name='Produit_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produit/prod_img')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomme.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecomme.section'),
        ),
        migrations.CreateModel(
            name='Information_suplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomme.produit')),
            ],
        ),
    ]
