# Generated by Django 4.2.4 on 2023-08-22 20:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomme', '0007_produit_section_alter_slider_titre_produit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='info_produit',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titre',
            field=models.CharField(choices=[('Nouvelle_arrivage', 'Nouvelle_arrivage'), ('Bonne_affaire', 'Bonne_affaire')], max_length=100),
        ),
    ]
